language: scala
jdk: oraclejdk8
scala:
  - 2.10.7
  - 2.11.12
  - 2.12.4
  - 2.13.0-M2
matrix:
  include:
  - scala: 2.12.4
    jdk: oraclejdk9
  - scala: 2.13.0-M3
    script:
    # TODO specs2 for Scala 2.13.0-M3
    - sbt "++${TRAVIS_SCALA_VERSION}!" 'project json4s-tests' 'set libraryDependencies ~= {_.filterNot(_.organization == "org.specs2")}' 'project /' compile
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
before_install:
  - export TZ=Australia/Canberra
script:
  - travis_retry sbt "++${TRAVIS_SCALA_VERSION}!" test
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
