language: scala
dist: precise
jdk: oraclejdk7
scala:
  - 2.10.6
  - 2.11.11
matrix:
  include:
  - scala: 2.12.3
    jdk: oraclejdk8
  - scala: 2.13.0-M2
    jdk: oraclejdk8
    script: sbt ++$TRAVIS_SCALA_VERSION compile
  - dist: trusty
    group: edge
    sudo: required
    scala: 2.12.3
    jdk: oraclejdk9
    script:
    - ./sbt -Dsbt.scala.version=2.10.7 ++$TRAVIS_SCALA_VERSION test
sudo: false
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
before_install:
  - export TZ=Australia/Canberra
script:
  - travis_retry sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues javaVersionCheck test
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
addons:
  apt:
    packages:
    - oracle-java8-installer
